name: Bug
description: バグ報告
title: "[Bug] "
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: 内容
      description: バグの詳細を記載してください
    validations:
      required: true
